[versions]
agp = "8.0.2"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1"}
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4"}

google-material = { module = "com.google.android.material:material", version = "1.9.0"}

tests-junit = { module = "junit:junit", version = "4.13.2" }
tests-google-truth = { module = "com.google.truth:truth", version = "1.1.4" }
tests-androidx-ext-junit = {  module = "androidx.test.ext:junit", version = "1.1.5" }
tests-androidx-espresso-core = {  module = "androidx.test.espresso:espresso-core", version = "3.5.1" }

gradle-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
maven-publish = { id = "com.vanniktech.maven.publish.base", version = "0.25.2" }